---
title: "TestDocument"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r,echo=FALSE, message=FALSE, results='asis',eval=FALSE}

library(xtable)
options(xtable.floating = FALSE)
options(xtable.timestamp = "")


DataDir<-"C:/Users/MRossi/Documents/03_Data/"
MetricsDir<- paste0(DataDir,"06_Metrics/")
pt<-readRDS(file = paste0(MetricsDir,"AllSensorData1608_byPlot.rds"))
print(xtable(pt),type="html",include.rownames = F)

```

```{r}

library(knitr)
library(kableExtra)
library(magrittr)
library(tidyverse)
library(magick)

asimage<-F

DataDir<-"C:/Users/MRossi/Documents/03_Data/"
MetricsDir<- paste0(DataDir,"06_Metrics/")

suffix<-"200818"
pt<-readRDS(file = paste0(MetricsDir,"AllSensorData",suffix,"_CorrelationAll.rds"))
pt1<-pt %>% replace(is.na(.), "")
data <- data.frame(lapply(pt1, function(x) { gsub("Decagon", "Decagon_SRS", x)}))

kable(data,"latex",booktabs=T,align="c",linesep=" ") %>% 
  kable_styling(latex_options = "scale_down") %>% 
  collapse_rows(1:2,row_group_label_position = "stack") %>% 
  add_header_above(c(" ","Sensors"=2," ","Plots"=4),align="c")
  
acq<-readRDS(file=paste0(MetricsDir,"AllData_byPlot.rds")) %>% replace(is.na(.), "")

kable(acq,"latex",booktabs=T,align="c",linesep=" ") %>% 
  kable_styling(latex_options = "scale_down") %>% 
  collapse_rows(1:2)%>% 
  add_header_above(c(" "=3,"Preprocessed"=5),align="c") 
  

kable(data,"html",booktabs=T,align="c",linesep=" ") %>% 
  kable_styling(latex_options = "scale_down") %>% 
  collapse_rows(1:2,row_group_label_position = "stack")

kable(acq,"html",booktabs=T,align="c",linesep=" ") %>% 
  kable_styling(latex_options = "scale_down") %>% 
  collapse_rows(1:2)


if(asimage==T){
  
  kableExtra::kable_as_image(k1, filename = paste0(MetricsDir,"Correlation_Table_All_byPlot"))
  kableExtra::kable_as_image(k2, filename = paste0(MetricsDir,"Acquisition_Table_All_byPlot"))
  
}

```


```{r}

rds<-readRDS(paste("../../rds/uno.spread.rds"))

pal.fnc = colorRamp(c("red", "yellow", "green"))
max.val<-1

rds<-rds %>% mutate(DOY=as.character(DOY)) %>% 
  rename(Combined=COMBINED) %>% 
  rename(SRS=Decagon_SRS) %>% 
  rename("Sentinel 2"=Sentinel2_MSI)

d = rds %>%
    mutate_if(is.numeric, function(x) {
  cell_spec(round(x,1), "latex", bold = F, color=grey(.3),
            background = rgb(pal.fnc(x/max.val) %>% replace(., is.na(.), 200), maxColorValue=255))
}) 

# Make 2 Columns

f1<-d %>% filter(Station=="Domef1500" | Station=="Domef2000")
f2<-d %>% filter(Station=="Vimef2000" | Station=="Vimes1500")


kheatL<-kable(f1, format ="latex", linesep="",booktabs = T,escape = F ,align = "c") %>% 
  kable_styling(latex_options = "scale_down") %>% 
  collapse_rows(1:2,row_group_label_position = "stack") %>% 
  add_header_above(c(" "=3,"Sensors"=4),align="c")


kheatR<-kable(f2, format ="latex", linesep="",booktabs = T,escape = F ,align = "c") %>% 
  kable_styling(latex_options = "scale_down") %>% 
  collapse_rows(1:2,row_group_label_position = "stack") %>% 
  add_header_above(c(" "=3,"Sensors"=4),align="c")

kableExtra::kable_as_image(kheatL, filename = "HeatmapL")
kableExtra::kable_as_image(kheatR, filename = "HeatmapR")

kableExtra::kable_as_image(cbind(kheatL,kheatR), filename = "HeatmapA")

```

Kable of the Spitab

```{r}
library(gplots)

spitab<-read.table(file = "../../spitab2.txt",header = T,sep = " ") %>% 
  as_tibble %>% 
  mutate(Index=as.factor(c(1:nrow(.))))

cols<- as.character(spitab$Color)
cols.hx<-col2hex(cols)

spitab<-spitab %>% 
  mutate(C2=map2_chr(rep("",nrow(.)),Color,function(x,y){
    
    cell_spec(x, "latex", bold = F, color=grey(.3),background = col2hex(y))
    
  }))

spitab2<- select(spitab, "SPI Regime"=Value,
         From,To,
         "Probability of\nEvent"=Probability,
         "Occurrence in\n100 years"=Frequency,
         Color=C2)

k1<-kable(spitab2,"latex",booktabs=T,align="c",linesep="",escape=F) %>% 
  kable_styling(latex_options = "scale_down") %>% 
  add_header_above(c(" "=1,"SPI Value Range"=2),align="c",) %>% 
  column_spec(c(1,4:5), width = "3cm")

kableExtra::kable_as_image(k1, filename = "Test")


```


# Field Campaign Table

```{r}

fctable<-readRDS("../../tables/fieldcampaigntable.rds")

fckable<-kable(fctable, format ="latex", linesep="",booktabs = T,escape = F ,align = "c") %>% 
  kable_styling(latex_options = "scale_down") %>% 
  collapse_rows(1:2,row_group_label_position = "stack") %>% 
  add_header_above(c(" "=4,"Field Campaign"=3),align="c")

kableExtra::kable_as_image(fckable, filename = "fctable")

```


# Indices Table

```{r}

sensors<-readRDS("../../tables/sensors.rds")

senskable<-kable(sensors, format ="latex", linesep="",booktabs = T,escape = F ,align = "c") %>% 
  add_header_above(c(" "=1,"Vegetation Indices"=6),align="c")
kableExtra::kable_as_image(senskable, filename = "senstable")

```




